version: "3"

services:
  mysql:
    image: mariadb/server:10.5
    hostname: mysql
    container_name: mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/mysql-beta:/var/lib/mysql
  web:
    container_name: web
    build: .
    ports:
      - 4000:3000
    volumes:
      - /home/ubuntu/.cache/yarn/beta:/usr/local/share/.cache/yarn/v6
    links:
      - mysql