version: "3"

services:
  mysql:
    image: mariadb/server:10.5
    container_name: mysqlBeta
    hostname: mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/mysql-beta:/var/lib/mysql
  koreanbots:
    container_name: koreanbots
    build: .
    ports:
      - 4000:3000
    env_file:
      - .env.production.local