name: Tests
on:
  - pull_request
  - push
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install
      run: yarn install
    - name: run eslint
      run: yarn lint
      env:
        CI: true
  test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Create needed files
      run: touch public.pem & touch .env.production.local & touch private.key & echo '{"tester":"DEMO_KEY"}' > secret.json
    - name: Docker Compose
      run: docker-compose up -d