name: CI
on:
  - pull_request
  - push
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install
      run: yarn install
    - name: run eslint
      run: yarn lint
      env:
        CI: true
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install
      run: yarn install
    - name: Generate RSA Key Pair
      run:  ssh-keygen -b 2048 -t rsa -f public -q -P "" & ssh-keygen -b 2048 -e -m pem -f public -q -P "" > private.key & mv public public.pem
    - name: Setup environments
      run: mv .env.demo.local .env.production.local & echo 'MYSQL_ROOT_PASSWORD=YOUSHALLNOTPASS' > .env
    - name: Create needed files
      run:  echo '{"tester":"DEMO_KEY"}' > secret.json
    - name: Build
      run: yarn build
      env:
        CI: true
  test:
    needs:
      - ESLint
      - Build
    name: Docker Image CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Generate RSA Key Pair
      run:  ssh-keygen -b 2048 -t rsa -f public -q -P "" & ssh-keygen -b 2048 -e -m pem -f public -q -P "" > private.key & mv public public.pem
    - name: Setup environments
      run: mv .env.demo.local .env.production.local & echo 'MYSQL_ROOT_PASSWORD=YOUSHALLNOTPASS' > .env
    - name: Create needed files
      run:  echo '{"tester":"DEMO_KEY"}' > secret.json
    - name: Docker Compose
      run: docker-compose up -d